baseURL = "https://antonz.ru/"
languageCode = "ru-ru"
title = "Антон Жиянов"
theme = "antonz"

enableRobotsTXT = true
rssLimit = 10

[permalinks]
posts = "/:slug"
years = "/:year"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "xcode"

[params]
author = "Антон Жиянов"
description = "Разработка софта, продуктоводство и здравый смысл"
